# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('itemid', models.IntegerField()),
                ('checkstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
