# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checkstatus',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='task',
            field=models.CharField(max_length=5000),
        ),
    ]
