# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDescription', models.CharField(max_length=200)),
                ('taskId', models.CharField(max_length=50)),
                ('taskGroupId', models.CharField(max_length=50)),
                ('taskStatus', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
