# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0005_auto_20191211_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list1.Group')),
            ],
        ),
    ]
