# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0007_auto_20191211_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
