# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0008_auto_20191211_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Group_Mapping',
            fields=[
                ('group_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
