# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0008_auto_20191211_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
