# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0009_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
