# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0009_user_group_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Group_Mapping',
        ),
        migrations.AddField(
            model_name='task',
            name='time_completed',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 27, 55, 668223)),
        ),
        migrations.AddField(
            model_name='task',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 27, 55, 668200)),
        ),
    ]
