# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0010_auto_20191213_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Group_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='time_completed',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 28, 9, 982469)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 28, 9, 982445)),
        ),
    ]
