# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0010_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTaskMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list1.Group')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list1.User')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
