# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import list1.models


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0011_auto_20191216_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptaskmapping',
            name='group_name',
            field=models.CharField(default='', max_length=30, verbose_name=list1.models.Group),
        ),
        migrations.AlterField(
            model_name='grouptaskmapping',
            name='group_id',
            field=models.CharField(default='', max_length=30, verbose_name=list1.models.Group),
        ),
        migrations.AlterField(
            model_name='grouptaskmapping',
            name='task_id',
            field=models.CharField(default='', max_length=30, verbose_name=list1.models.User),
        ),
    ]
