# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0011_auto_20191213_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_group_mapping',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='list1.Group'),
        ),
        migrations.AddField(
            model_name='user_group_mapping',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='list1.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_completed',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 29, 8, 895059)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 6, 29, 8, 895034)),
        ),
    ]
