# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0012_auto_20191216_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptaskmapping',
            old_name='task_id',
            new_name='user_id',
        ),
    ]
