# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0013_auto_20191216_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptaskmapping',
            old_name='group_name',
            new_name='title',
        ),
    ]
