# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list1', '0015_group_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='is_public',
            new_name='type',
        ),
    ]
